import "./globals.css";
import { StateContext } from "@/context/StateContext";
import { Footer, Header } from "@/components";
import { Toaster } from "react-hot-toast";
import ThemeContextProvider from "@/context/ThemeContext";

export const metadata = {
  title: "GSHOP | Buy Top Video Games",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const theme = window.localStorage.getItem('theme');
                if (theme) {
                  document.documentElement.classList.add(theme === 'dark' ? 'dark' : '');
                } else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
                  document.documentElement.classList.add('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body>
        <ThemeContextProvider>
          <StateContext>
            <Header />
            <Toaster />
            {children}
            <Footer />
          </StateContext>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
