import "./globals.css";
import { StateContext } from "@/context/StateContext";
import { Footer, Header } from "@/components";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "GSHOP | Buy Top Video Games",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-[100%] bg bg-bgcol font-sans
      overflow-y-scroll scrollbar-w-2 scrollbar
      scrollbar-thumb-red hover:scrollbar-thumb-[#9f9f9f]
      "
    >
      <body>
        <StateContext>
          <Header />
          <Toaster />
          {children}
          <Footer />
        </StateContext>
      </body>
    </html>
  );
}
